# Generated by Django 5.1 on 2024-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_comment_options_remove_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField()),
                ('status', models.CharField(choices=[('R', 'Read'), ('A', 'Added'), ('P', 'Pending Review/Comment'), ('I', 'In Progress'), ('C', 'Completed'), ('D', 'Discarded')], default='R', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='major_findings',
            field=models.TextField(max_length=800),
        ),
    ]
