# Generated by Django 5.1 on 2024-08-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_status_alter_comment_date_alter_comment_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='status',
            field=models.ManyToManyField(to='main_app.status'),
        ),
    ]
