# Generated by Django 5.1 on 2024-08-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_researchpaper_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('keywords', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='status',
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='themes',
            field=models.ManyToManyField(to='main_app.theme'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
