# Generated by Django 5.1 on 2024-08-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
