# Generated by Django 5.1 on 2024-08-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_researchpaper_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='entire_paper',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
