# Generated by Django 5.1 on 2024-08-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_researchpaper_entire_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='color',
        ),
    ]
